trigger:
  branches:
    include:
      - main

variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '8.x'
  azureSubscription: 'MR552824-ELLIE-DE-OLIVEIRA (15e7a2ee-5628-4d7f-a4ba-455b7c975eaf)'  # Azure DevOps service connection name
  appName: 'api-safezone'                          # Azure Web App name
  resourceGroupName: 'rg-safezone-prod'            # Azure Resource Group
  webAppPackagePath: '$(Build.ArtifactStagingDirectory)/publish'

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '$(dotnetSdkVersion)'

          - task: NuGetToolInstaller@1

          - checkout: self

          - task: DotNetCoreCLI@2
            displayName: 'Restore NuGet packages'
            inputs:
              command: 'restore'
              projects: 'api-safezone-cs/*.csproj'

          - task: DotNetCoreCLI@2
            displayName: 'Build project'
            inputs:
              command: 'build'
              projects: 'api-safezone-cs/*.csproj'
              arguments: '--configuration $(buildConfiguration)'

          - task: DotNetCoreCLI@2
            displayName: 'Publish app'
            inputs:
              command: 'publish'
              projects: 'api-safezone-cs/*.csproj'
              arguments: '--configuration $(buildConfiguration) --output $(webAppPackagePath)'
              zipAfterPublish: true

          - task: PublishBuildArtifacts@1
            displayName: 'Publish build artifacts'
            inputs:
              PathtoPublish: '$(webAppPackagePath)'
              ArtifactName: 'app'
              publishLocation: 'Container'

  - stage: Deploy
    displayName: 'Deploy Stage'
    dependsOn: Build
    jobs:
      - job: DeployWebApp
        displayName: 'Deploy to Azure Web App'
        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'app'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webApp'
              appName: '$(appName)'
              package: '$(System.ArtifactsDirectory)/app/**/*.zip'
