version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Porta usada pelos clientes (ex: sua API)
      - "15672:15672"   # UI do RabbitMQ (acesso via navegador)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge
