// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using api_safezone_cs.Data.AppData;

#nullable disable

namespace api_safezone_cs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api_safezone_cs.Domain.Entities.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaAfetada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Severidade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("api_safezone_cs.Domain.Entities.Ocorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Prioridade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("Ocorrencias");
                });

            modelBuilder.Entity("api_safezone_cs.Domain.Entities.Vitima", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Condicao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Idade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("OcorrenciaId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("OcorrenciaId");

                    b.ToTable("Vitimas");
                });

            modelBuilder.Entity("api_safezone_cs.Domain.Entities.Ocorrencia", b =>
                {
                    b.OwnsOne("api_safezone_cs.Domain.Entities.Localizacao", "Localizacao", b1 =>
                        {
                            b1.Property<int>("OcorrenciaId")
                                .HasColumnType("NUMBER(10)");

                            b1.Property<string>("Latitude")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("NVARCHAR2(11)");

                            b1.Property<string>("Longitude")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("NVARCHAR2(12)");

                            b1.HasKey("OcorrenciaId");

                            b1.ToTable("Ocorrencias");

                            b1.WithOwner()
                                .HasForeignKey("OcorrenciaId");
                        });

                    b.Navigation("Localizacao")
                        .IsRequired();
                });

            modelBuilder.Entity("api_safezone_cs.Domain.Entities.Vitima", b =>
                {
                    b.HasOne("api_safezone_cs.Domain.Entities.Ocorrencia", "Ocorrencia")
                        .WithMany("Vitimas")
                        .HasForeignKey("OcorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("api_safezone_cs.Domain.Entities.Localizacao", "Localizacao", b1 =>
                        {
                            b1.Property<int>("VitimaId")
                                .HasColumnType("NUMBER(10)");

                            b1.Property<string>("Latitude")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("NVARCHAR2(11)");

                            b1.Property<string>("Longitude")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("NVARCHAR2(12)");

                            b1.HasKey("VitimaId");

                            b1.ToTable("Vitimas");

                            b1.WithOwner()
                                .HasForeignKey("VitimaId");
                        });

                    b.Navigation("Localizacao")
                        .IsRequired();

                    b.Navigation("Ocorrencia");
                });

            modelBuilder.Entity("api_safezone_cs.Domain.Entities.Ocorrencia", b =>
                {
                    b.Navigation("Vitimas");
                });
#pragma warning restore 612, 618
        }
    }
}
